server:
  port: 8088
spring:
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://127.0.0.1:3306/customer?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
mybatis:
  mapper-locations: classpath*:/com/coin/mapper/*.xml
  type-aliases-package: com.coin.entity