server:
  port: 8088
spring:
  datasource:
    username: root1
    password: y8sDksW3ScwcHAKL
    url: jdbc:mysql://127.0.0.1:3306/customer?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: redisPlus
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 0
        min-idle: 0
mybatis:
  mapper-locations: classpath*:/com/coin/mapper/*.xml
  type-aliases-package: com.coin.entity