spring:
  profiles:
    active: uat
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
mybatis:
  mapper-locations: classpath*:com/coin/mapper/*.xml,classpath*:com/coin/mapper/dao/*.xml
  type-aliases-package: com.coin.entity
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
  auto-dialect: mysql
ok:
  http:
    connect-timeout: 3
    read-timeout: 8
    write-timeout: 8
    keep-alive-duration: 60
    max-idle-connections: 5