spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  mvc:
    view:
      prefix: /static/html/
      suffix: .html
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath*:/com/coin/mapper/*.xml
  type-aliases-package: com.coin.entity
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
  auto-dialect: mysql
ok:
  http:
    connect-timeout: 3
    read-timeout: 30
    write-timeout: 30
    keep-alive-duration: 60
    max-idle-connections: 5