spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  mvc:
    view:
      prefix: /static/html/
      suffix: .html
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath*:/com/coin/mapper/*.xml
  type-aliases-package: com.coin.entity